[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
  -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  majicdesigns/MD_MAX72XX @ ^3.5.1
  links2004/WebSockets @ ^2.4.1
  bblanchon/ArduinoJson @ ^6.21.5
